ALTER TABLE projects ADD COLUMN discount_percentage NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN eighty_twenty_rate NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN lca_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
